<aside>
	<h2>Navigation</h2>
	<ul>
		<li><?php echo anchor('privacy_policy#limitation_of_liability_for_internal_content', 'Limitation&nbsp;of&nbsp;liability&nbsp;for&nbsp;internal&nbsp;content'); ?></li>
		<li><?php echo anchor('privacy_policy#limitation_of_liability_for_external_links', 'Limitation&nbsp;of&nbsp;liability&nbsp;for&nbsp;external&nbsp;links'); ?></li>
		<li><?php echo anchor('privacy_policy#copyright', 'Copyright'); ?></li>
		<li><?php echo anchor('privacy_policy#data_protection', 'Data protection'); ?></li>
		<li><?php echo anchor('privacy_policy#google_analytics', 'Google Analytics'); ?></li>
	</ul>
	<br class="clear" />
</aside>


<section id="content">
	
	<section id="limitation_of_liability_for_internal_content">	    	
		<header>
			<h2>Limitation of liability for internal content</h2>
		</header>
			
		<article>
			The content of our website has been compiled with meticulous care and to the best of our knowledge. However, we cannot assume any liability for the up-to-dateness, completeness or accuracy of any of the pages.<br />
			<br />
			Pursuant to section 7, para. 1 of the TMG (Telemediengesetz –  Tele Media Act by German law), we as service providers are liable for our own content on these pages in accordance with general laws. However, pursuant to sections 8 to 10 of the TMG, we as service providers are not under obligation to monitor external information provided or stored on our website. Once we have become aware of a specific infringement of the law, we will immediately remove the content in question. Any liability concerning this matter can only be assumed from the point in time at which the infringement becomes known to us.
		</article>
	</section>
	
	<section id="limitation_of_liability_for_external_links">	    	
		<header>
			<h2>Limitation of liability for external links</h2>
		</header>
			
		<article>
			Our website contains links to the websites of third parties (“external links”). As the content of these websites is not under our control, we cannot assume any liability for such external content. In all cases, the provider of information of the linked websites is liable for the content and accuracy of the information provided. At the point in time when the links were placed, no infringements of the law were recognisable to us. As soon as an infringement of the law becomes known to us, we will immediately remove the link in question.
		</article>
	</section>
	
	<section id="copyright">	    	
		<header>
			<h2>Copyright</h2>
		</header>
			
		<article>
			The content and works published on this website are governed by the copyright laws of Germany. Any duplication, processing, distribution or any form of utilisation beyond the scope of copyright law shall require the prior written consent of the author or authors in question.
		</article>
	</section>
	
	<section id="data_protection">	    	
		<header>
			<h2>Data protection</h2>
		</header>
			
		<article>
			A visit to our website can result in the storage on our server of information about the access (date, time, page accessed). This does not represent any analysis of personal data (e.g., name, address or e-mail address). If personal data are collected, this only occurs – to the extent possible – with the prior consent of the user of the website. Any forwarding of the data to third parties without the express consent of the user shall not take place.<br />
			We would like to expressly point out that the transmission of data via the Internet (e.g., by e-mail) can offer security vulnerabilities. It is therefore impossible to safeguard the data completely against access by third parties. We cannot assume any liability for damages arising as a result of such security vulnerabilities.<br />
			The use by third parties of all published contact details for the purpose of advertising is expressly excluded. We reserve the right to take legal steps in the case of the unsolicited sending of advertising information; e.g., by means of spam mail.
		</article>
	</section>
	
	<p>Source: <a href="http://www.rosepartner.de/en">Rose &amp; Partner LLP.</a></p>
	
	<section id="google_analytics">	    	
		<header>
			<h2>Google Analytics</h2>
		</header>
			
		<article>
			This website uses Google Analytics, a web analytics service provided by Google Inc. (" Google "). <br />
			Google Analytics uses "cookies", text files that are stored on your computer and allow an analysis of the use of the website. <br />
			The information generated by the cookie about your use of this site are usually sent to a server of Google in the U.S. and stored there. <br />
			In the case of activation of the IP anonymization on this Web site, <br />
			the IP address of Google will be truncated within Member States of the European Union or other parties to the Agreement on the European Economic Area before. <br />
			Only in exceptional cases, the full IP address is sent to a Google server in the USA and is shortened. On behalf of the operator of this site Google will use this information to evaluate your use of the website, <br />
			compiling reports on website activity together and to provide other with website and internet related services to the site operator. <br />
			Which is within the scope of Google Analytics that your browser sends IP address can not be merged with other data held by Google. <br />
			You can prevent the storage of cookies by selecting the appropriate settings on your browser, we point out, however, that in this case not all the features of this site are in full use. <br />
			You can also extend the coverage of the generated by the cookie and prevent your use of the site-related data (including your IP address) to Google and the processing of these data by Google, <br />
			by the following at the link <a href="http://tools.google.com/dlpage/gaoptout?hl=en" class="none solid">http://tools.google.com/dlpage/gaoptout?hl=en</a> Download and install the browser plug-in available.
		</article>
	</section>
	
</section>